# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 585)
        MainWindow.setStyleSheet("#widget_2{\n"
"    background-color: #F1F1F1;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("#widget_3,#widget_4,#widget_5{\n"
"    border-bottom: 1.5px solid #DCDCDC;\n"
"    background-color: #F1F1F1;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.widget_3.setFont(font)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 125))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(21)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(22)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(23)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(24)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(25)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(26)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(27)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(28)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(29)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(30)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(31)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(32)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(33)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(34)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(35)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "柏乐佳"))

