# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 483)
        MainWindow.setStyleSheet("#widget_2{\n"
"    border-left: 12px;\n"
"    background-color: #fff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(130, 16777215))
        self.widget.setStyleSheet("#widget_7{\n"
"    background-color: #F7F7F7;\n"
"}\n"
"#listWidget{\n"
"    border: none;\n"
"    background-color:#F7F7F7;\n"
"}\n"
"#widget_8{\n"
"    background-color: #59BAF3;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_7.setStyleSheet("#searchOradd{\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    background-color:#ECECEC;\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.searchOradd = QtWidgets.QLineEdit(self.widget_7)
        self.searchOradd.setGeometry(QtCore.QRect(7, 10, 95, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchOradd.setFont(font)
        self.searchOradd.setStyleSheet("    background-color:#ECECEC;")
        self.searchOradd.setObjectName("searchOradd")
        self.add_btn = QtWidgets.QPushButton(self.widget_7)
        self.add_btn.setGeometry(QtCore.QRect(107, 10, 20, 21))
        self.add_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.add_btn.setMaximumSize(QtCore.QSize(31, 31))
        self.add_btn.setText("")
        self.add_btn.setIconSize(QtCore.QSize(16, 16))
        self.add_btn.setAutoDefault(False)
        self.add_btn.setDefault(False)
        self.add_btn.setFlat(False)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.widget_7)
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_8.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.add_friend_msg = QtWidgets.QLabel(self.widget_8)
        self.add_friend_msg.setGeometry(QtCore.QRect(7, 3, 121, 16))
        self.add_friend_msg.setObjectName("add_friend_msg")
        self.agree_btn = QtWidgets.QPushButton(self.widget_8)
        self.agree_btn.setGeometry(QtCore.QRect(20, 14, 28, 28))
        self.agree_btn.setText("")
        self.agree_btn.setIconSize(QtCore.QSize(19, 19))
        self.agree_btn.setObjectName("agree_btn")
        self.refuse_btn = QtWidgets.QPushButton(self.widget_8)
        self.refuse_btn.setGeometry(QtCore.QRect(80, 13, 28, 28))
        self.refuse_btn.setText("")
        self.refuse_btn.setIconSize(QtCore.QSize(20, 20))
        self.refuse_btn.setObjectName("refuse_btn")
        self.verticalLayout.addWidget(self.widget_8)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.widget_3.setFont(font)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.chatObject = QtWidgets.QLabel(self.widget_3)
        self.chatObject.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.chatObject.setFont(font)
        self.chatObject.setText("")
        self.chatObject.setObjectName("chatObject")
        self.vboxlayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setItalic(False)
        self.widget_4.setFont(font)
        self.widget_4.setStyleSheet("#chatShow{\n"
"    border: none;\n"
"}\n"
"#emoji_container{\n"
"    border: 1px solid black;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setGeometry(QtCore.QRect(180, 130, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.chatShow = QtWidgets.QTextEdit(self.widget_4)
        self.chatShow.setGeometry(QtCore.QRect(0, 0, 510, 276))
        self.chatShow.setReadOnly(True)
        self.chatShow.setObjectName("chatShow")
        self.emoji_container = QtWidgets.QWidget(self.widget_4)
        self.emoji_container.setGeometry(QtCore.QRect(0, 140, 171, 131))
        self.emoji_container.setStyleSheet("border-radius: 10px;")
        self.emoji_container.setObjectName("emoji_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.emoji_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.emoji_1 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_1.setObjectName("emoji_1")
        self.horizontalLayout_2.addWidget(self.emoji_1)
        self.emoji_2 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_2.setObjectName("emoji_2")
        self.horizontalLayout_2.addWidget(self.emoji_2)
        self.emoji_3 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_3.setObjectName("emoji_3")
        self.horizontalLayout_2.addWidget(self.emoji_3)
        self.emoji_4 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_4.setObjectName("emoji_4")
        self.horizontalLayout_2.addWidget(self.emoji_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.emoji_5 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_5.setObjectName("emoji_5")
        self.horizontalLayout_3.addWidget(self.emoji_5)
        self.emoji_6 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_6.setObjectName("emoji_6")
        self.horizontalLayout_3.addWidget(self.emoji_6)
        self.emoji_7 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_7.setObjectName("emoji_7")
        self.horizontalLayout_3.addWidget(self.emoji_7)
        self.emoji_8 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_8.setObjectName("emoji_8")
        self.horizontalLayout_3.addWidget(self.emoji_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.emoji_9 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_9.setObjectName("emoji_9")
        self.horizontalLayout_4.addWidget(self.emoji_9)
        self.emoji_10 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_10.setObjectName("emoji_10")
        self.horizontalLayout_4.addWidget(self.emoji_10)
        self.emoji_11 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_11.setObjectName("emoji_11")
        self.horizontalLayout_4.addWidget(self.emoji_11)
        self.emoji_12 = QtWidgets.QPushButton(self.emoji_container)
        self.emoji_12.setObjectName("emoji_12")
        self.horizontalLayout_4.addWidget(self.emoji_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.chatShow.raise_()
        self.label.raise_()
        self.emoji_container.raise_()
        self.vboxlayout.addWidget(self.widget_4)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_6.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:#fff;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.send_emoji_btn = QtWidgets.QPushButton(self.widget_6)
        self.send_emoji_btn.setGeometry(QtCore.QRect(10, 0, 30, 30))
        self.send_emoji_btn.setAutoFillBackground(False)
        self.send_emoji_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imgs/icon/smile.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_emoji_btn.setIcon(icon)
        self.send_emoji_btn.setIconSize(QtCore.QSize(23, 23))
        self.send_emoji_btn.setObjectName("send_emoji_btn")
        self.send_file_btn = QtWidgets.QPushButton(self.widget_6)
        self.send_file_btn.setGeometry(QtCore.QRect(44, 0, 30, 30))
        self.send_file_btn.setAutoFillBackground(False)
        self.send_file_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../imgs/icon/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_file_btn.setIcon(icon1)
        self.send_file_btn.setIconSize(QtCore.QSize(23, 23))
        self.send_file_btn.setObjectName("send_file_btn")
        self.look_history_btn = QtWidgets.QPushButton(self.widget_6)
        self.look_history_btn.setGeometry(QtCore.QRect(80, 0, 30, 30))
        self.look_history_btn.setAutoFillBackground(False)
        self.look_history_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../imgs/icon/history.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.look_history_btn.setIcon(icon2)
        self.look_history_btn.setIconSize(QtCore.QSize(23, 23))
        self.look_history_btn.setObjectName("look_history_btn")
        self.vboxlayout.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 125))
        self.widget_5.setStyleSheet("#msgContainer{\n"
"    border: none;\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.msgContainer = QtWidgets.QTextEdit(self.widget_5)
        self.msgContainer.setEnabled(True)
        self.msgContainer.setGeometry(QtCore.QRect(0, 0, 518, 125))
        self.msgContainer.setObjectName("msgContainer")
        self.sendMsg_btn = QtWidgets.QPushButton(self.widget_5)
        self.sendMsg_btn.setGeometry(QtCore.QRect(430, 90, 70, 32))
        self.sendMsg_btn.setObjectName("sendMsg_btn")
        self.vboxlayout.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "聊天"))
        self.searchOradd.setPlaceholderText(_translate("MainWindow", "搜索/添加"))
        self.add_friend_msg.setText(_translate("MainWindow", "朱石磊请求添加好友"))
        self.label.setText(_translate("MainWindow", "Python For Chat"))
        self.emoji_1.setText(_translate("MainWindow", "😀"))
        self.emoji_2.setText(_translate("MainWindow", "😍"))
        self.emoji_3.setText(_translate("MainWindow", "😂"))
        self.emoji_4.setText(_translate("MainWindow", "😅"))
        self.emoji_5.setText(_translate("MainWindow", "🥺"))
        self.emoji_6.setText(_translate("MainWindow", "😘"))
        self.emoji_7.setText(_translate("MainWindow", "🙁"))
        self.emoji_8.setText(_translate("MainWindow", "😤"))
        self.emoji_9.setText(_translate("MainWindow", "😡"))
        self.emoji_10.setText(_translate("MainWindow", "🤔"))
        self.emoji_11.setText(_translate("MainWindow", "👍"))
        self.emoji_12.setText(_translate("MainWindow", "🐶"))
        self.sendMsg_btn.setText(_translate("MainWindow", "发送"))

